version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: auth_api
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5433:5432"  # host:container (5433 to avoid conflict with other local Postgres)

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8002:8000"  # 8002 to avoid conflict with other local apps
    env_file:
      - ./.env
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=auth_api
      - DB_USER=auth_user
      - DB_PASS=auth_pass
    depends_on:
      - db

volumes:
  postgres_data:
